import React from "react";
import "./style.scss";
function Animation() {
  return (
  
    <div className="Animation">
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          src="https://xspace.uz/wp-content/uploads/2020/06/logo-04.jpg"
          alt=""
        />
      </div>
    </div>
    
  );
}

export default Animation;
