const portfolioMenu = [
  {
    id: 1,
    title: "Alo study center",
    category: "Design",
    img: "https://wallpaperaccess.com/full/465921.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "Kiwi",
    category: "Branding",
    img: "https://wallpaperaccess.com/full/465921.jpg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "Cosco",
    category: "Web",
    img: "https://wallpaperaccess.com/full/465921.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "Mazza",
    category: "Design",
    img: "https://wallpaperaccess.com/full/465921.jpg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "Nasa",
    category: "Branding",
    img: "https://wallpaperaccess.com/full/465921.jpg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "Mumtoz",
    category: "Web",
    img: "https://wallpaperaccess.com/full/465921.jpg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "Design",
    img: "https://wallpaperaccess.com/full/465921.jpg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "american classic",
    category: "Branding",
    img: "https://wallpaperaccess.com/full/465921.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "Web",
    img: "https://wallpaperaccess.com/full/465921.jpg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default portfolioMenu;
